# Generated by Django 3.2.10 on 2021-12-19 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount')),
                ('date_begin', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_task.product', verbose_name='Product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='discount')),
                ('date_begin', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_task.category', verbose_name='Category')),
            ],
        ),
    ]
